name: build container image
on:
  workflow_dispatch
#   push:
#     branches: 
#     - main
jobs: 
  scale-up: 
    runs-on: [self-hosted, base, dev]
    steps:
    - name: Scale deployment
      run: | 
        kubectl scale deployment buildah-runner --replicas 3
        
  versioning: 
    needs: [scale-up]
    runs-on: [self-hosted, buildah, dev]
    outputs: 
      version: ${{env.date}}
    steps:
    - name: Set The Image Tag
      id: date
      run: echo "date=$(date +'%Y-%m.%d.%H%M')" >> $GITHUB_ENV

  build:
    needs: [versioning]
    runs-on: [self-hosted, buildah, dev]
    steps: 
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build image using buildah
      run: | 
        buildah bud -f /home/runner/_work/vue-quickstart/vue-quickstart/Dockerfile --format docker --tls-verify=false -t quay.io/andygodish/vue-quickstart:${{ needs.versioning.outputs.version }}


  push:
    needs: [versioning, build]
    runs-on: [self-hosted, buildah, dev]
    steps: 
    - name: Push image
      run: | 
        buildah login -u="andygodish+vuequickstart" -p=${{ secrets.QUAY_PASSWORD }} quay.io
        buildah push quay.io/andygodish/vue-quickstart:${{ needs.versioning.outputs.version }}
  
  scale-down: 
    needs: [push]
    runs-on: [self-hosted, base, dev]
    steps:
    - name: Scale deployment
      run: | 
        kubectl scale deployment buildah-runner --replicas 0
  
